
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module SDRAM_to_VGA(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// VGA //////////
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

main2 u1(.rstn(KEY[0]),
.clk50(MAX10_CLK1_50), .B(VGA_B),
.G(VGA_G), .R(VGA_R), .Hsync(VGA_HS), .Vsync(VGA_VS),
.DRAM_ADDR(DRAM_ADDR),
.DRAM_BA(DRAM_BA),
.DRAM_CAS_N(DRAM_CAS_N),
.DRAM_CKE(DRAM_CKE),
.DRAM_CLK(DRAM_CLK),
.DRAM_CS_N(DRAM_CS_N),
.DRAM_DQ(DRAM_DQ),
.DRAM_LDQM(DRAM_LDQM),
.DRAM_RAS_N(DRAM_RAS_N),
.DRAM_UDQM(DRAM_UDQM),
.DRAM_WE_N(DRAM_WE_N)
);

endmodule
